spring.application.name=pet
# Configuración de base de datos H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar la consola H2 (accesible en /h2-console)
spring.h2.console.enabled=true

# Mostrar SQL en consola (opcional, útil para depuración)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

# Credenciales fijas para desarrollo
spring.security.user.name=admin
spring.security.user.password=admin123
app.admin.email=admin@veterinaria.local
app.admin.password=Admin123*
jwt.secret=Q2xhdmVTZWNyZXRhTXV5U2VndXJhUGFyYUxhQ2xpbmljYVZldGVyaW5hcmlhMjAyNA==
google.oauth.client-id=521550630523-93d0q4018c94g63r0p41qldslmh1emp6.apps.googleusercontent.com


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ldtb2001@gmail.com
spring.mail.password=zhav sdut tirj ksvh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true